#!/bin/bash

export KUBERNETES_VERSION=${KUBERNETES_VERSION:-"v1.20.4"}
export KUBERNETES_BINARIES_CONFIG_VERSION=${KUBERNETES_BINARIES_CONFIG_VERSION:-"v0.2.7"}
export CRICTL_VERSION=${CRICTL_VERSION:-"v1.20.0"}
export OS=${OS:-"xUbuntu_20.04"}
export VERSION=${VERSION:-"1.20"}